spring.datasource.url=jdbc:postgresql://localhost:5432/players_db
spring.datasource.username=superuser
spring.datasource.password=superuser

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jackson.property-naming-strategy=SNAKE_CASE

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.web=DEBUG
logging.level.org.oop.lab3=DEBUG